### ISSUE TITLE
Los almacenes pueden estar en mantenimiento?

### ISSUE THREAD

**Issue by Altro31** [Proyecto-Bookcase/BillingSystem#35]
De ser así, falta el atributo maintenance en WarehouseDto

**Comment by Dialcr** [comment]
si

**Comment by Altro31** [comment]
Tienen un atributo que lo diga, o solo si todaa sus ubicaciones están en mantenimiento
________________________________
De: Dialcr ***@***.***>
Enviado: domingo, 17 de diciembre de 2023 19:56
Para: Proyecto-Bookcase/BillingSystem ***@***.***>
Cc: Altro ***@***.***>; Author ***@***.***>
Asunto: Re: [Proyecto-Bookcase/BillingSystem] Los almacenes pueden estar en mantenimiento? (Issue #35)


si
